### ISSUE TITLE
Suddenly not allowed in Chrome (MS Edge)

### ISSUE THREAD

**Issue by enthous** [vjestin/paprika-bookmarklet#3]
I've been using this bookmarklet for years.  Suddenly it's been disabled in my MS Edge browser saying: 
 "This extension has been turned off as it's been marked unsafe by the Chrome Web Store."

I cannot seem to override this.

**Comment by vjestin** [comment]
Yes, I need to update the extension to comply with new policy from Google. Work in progress.

**Comment by enthous** [comment]
Thank you.  Will you post here when it's available please?

**Comment by JohanSF** [comment]
Its been almost 6 months, any updates on this?

**Comment by vjestin** [comment]
It's over. This extension does exactly what new Google Chrome security policy wants to avoid. This is a "David vs Goliath" kind of fight I'm not willing to have.
The extension is removed from Google Chrome webstore and this repo will be moved to private soon.

If you want to use [Paprika bookmarklet](https://www.paprikaapp.com/bookmarklet/), you will have to install it... as a bookmarklet!
